"""Environment secrets.

`env.<VAR>` in the vault becomes `export VAR=...` in a file the shell sources,
so a new shell pays no vault-unlock cost at startup.

There is no map from variable names to vault items: the `env` section is the
set. That is the whole point of storing everything under one item -- there is
nothing to keep in sync and nothing to leave behind.
"""

import os
import re
import shlex
import tempfile
from pathlib import Path

from .errors import KeyvaultError
from .paths import section

# POSIX environment variable names. Narrower than a path segment, which also
# allows "-", so a storable path is not necessarily an exportable name.
ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

HEADER = (
    "# Generated by keyvault. Do not edit.\n"
    "# The vault is the source of truth; run `keyvault secrets sync`.\n"
)


def env_file() -> Path:
    return Path.home() / ".zshenv.secrets"


def values(fields: dict[str, str]) -> dict[str, str]:
    """The env section, rejecting names a shell could not export."""
    found = section(fields, "env")
    if bad := sorted(name for name in found if not ENV_NAME_RE.match(name)):
        raise KeyvaultError(
            f"not usable as environment variable names: {', '.join(bad)}"
        )
    return found


def render(values: dict[str, str]) -> str:
    lines = (
        f"export {name}={shlex.quote(value)}" for name, value in sorted(values.items())
    )
    return HEADER + "".join(f"{line}\n" for line in lines)


def write(text: str, path: Path) -> None:
    """Replace `path` atomically, never leaving it world-readable."""
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary = tempfile.mkstemp(dir=path.parent, prefix=".keyvault-")
    try:
        with os.fdopen(handle, "w") as stream:
            stream.write(text)
        os.chmod(temporary, 0o600)
        os.replace(temporary, path)
    except BaseException:
        os.unlink(temporary)
        raise


def check_name(name: str) -> None:
    if not ENV_NAME_RE.match(name):
        raise KeyvaultError(
            f"{name!r} is not a usable environment variable name "
            "([A-Za-z_][A-Za-z0-9_]*)"
        )
