"""SSH key operations.

The vault stores private keys and nothing else: `ssh.<name>` is the private
key. Public keys and fingerprints are derived from it on demand, so there is
one copy of each key and no way for the two halves to disagree.

Keys are generated by `ssh-keygen` rather than in-process, because serialising
the OpenSSH private key format by hand is the wrong thing to get subtly wrong.
`ssh-keygen` cannot generate to stdout, so `generate` writes to the key's
permanent home under ~/.ssh; a machine key belongs on that machine's disk.
Deriving a public key also needs a file, because ssh-keygen rejects a private
key read from a pipe on macOS -- that one uses a 0600 file in a 0700 temporary
directory, removed immediately.
"""

import os
import socket
import subprocess
import sys
import tempfile
from pathlib import Path

from .errors import KeyvaultError
from .paths import SEGMENT_RE, section

KEY_TYPE = "ed25519"

# The recovery key, deliberately awkward to load: it exists so that no host is
# ever one lost key away from being unreachable.
MASTER = "master"


def default_name() -> str:
    """This machine's key name: the short hostname, lowercased."""
    name = socket.gethostname().split(".")[0].lower()
    if not SEGMENT_RE.match(name):
        raise KeyvaultError(
            f"hostname {name!r} is not usable as a key name; pass one explicitly"
        )
    return name


def key_path(name: str) -> Path:
    return Path.home() / ".ssh" / f"id_{name}"


def names(fields: dict[str, str]) -> list[str]:
    """The key names stored in the vault."""
    return sorted(section(fields, "ssh"))


def private_key(fields: dict[str, str], name: str) -> str:
    if (private := fields.get(f"ssh.{name}")) is None:
        raise KeyvaultError(f"the vault holds no key named {name!r}")
    return private


def public_key(private: str) -> str:
    """Derive the public key. Fails rather than prompting for a passphrase.

    Goes through a private temporary file rather than /dev/stdin: on macOS a
    pipe is mode 0660, and ssh-keygen refuses to read a private key from
    anything group-readable. On Linux the same pipe is 0600, which is why this
    only fails on a Mac.
    """
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "key"
        # Created 0600 outright rather than chmod-ed after, so the key is never
        # briefly readable even inside the 0700 directory.
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(descriptor, "w") as handle:
            handle.write(private)
        return _run("ssh-keygen", "-y", "-f", str(path)).strip()


def fingerprint(private: str) -> str:
    return _run("ssh-keygen", "-lf", "-", stdin=public_key(private)).strip()


def find_duplicate(fields: dict[str, str], private: str, *, ignore: str) -> str | None:
    """The name of a stored key with the same material, if there is one.

    Compares public halves: they are canonical, whereas two encodings of the
    same private key can differ byte for byte.
    """
    wanted = public_key(private)
    for name in names(fields):
        if name != ignore and public_key(fields[f"ssh.{name}"]) == wanted:
            return name
    return None


# An authorized_keys line may carry an options prefix before the key type,
# e.g. `restrict,from="10.0.0.0/8" ssh-ed25519 AAAA... comment`.
KEY_TYPE_PREFIXES = ("ssh-", "ecdsa-", "sk-")


def key_material(line: str) -> str | None:
    """The `<type> <base64>` of an authorized_keys line, or None if there is none.

    Ignores any options prefix and the trailing comment, both of which differ
    between copies of the same key and must not affect identity.
    """
    fields = line.split()
    for index, field in enumerate(fields):
        if field.startswith(KEY_TYPE_PREFIXES) and index + 1 < len(fields):
            return f"{field} {fields[index + 1]}"
    return None


def authorized_line(name: str, private: str) -> str:
    """Render a vault key as an authorized_keys line.

    Comments the line `keyvault:<name>` so a later deploy -- or a human reading
    the file on the host -- can tell which vault entry put it there. That is the
    problem an unlabelled key on a router creates.
    """
    return f"{key_material(public_key(private))} keyvault:{name}"


def classify(text: str, materials: dict[str, str]) -> list[tuple[str | None, str]]:
    """Pair each authorized_keys line with the vault key name it matches.

    `materials` maps vault key name to its `key_material`. Lines that match
    nothing come back with None rather than being dropped: an unrecognised key
    may be a colleague or a CI system, and silently removing it would be worse
    than leaving it.
    """
    by_material = {material: name for name, material in materials.items()}
    entries = []
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        material = key_material(line)
        entries.append((by_material.get(material) if material else None, line))
    return entries


def generate(name: str, path: Path) -> str:
    """Generate an ed25519 key at `path`, returning the private key."""
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    public_path = Path(f"{path}.pub")
    if path.exists() or public_path.exists():
        raise KeyvaultError(f"{path} already exists")
    _run("ssh-keygen", "-q", "-t", KEY_TYPE, "-N", "", "-C", name, "-f", str(path))
    return path.read_text()


def read_key(source: Path | None) -> str:
    """Read a private key from a file, or from stdin when `source` is None.

    Normalises line endings and the trailing newline, then proves the result
    parses by deriving its public half. Both matter for a key pasted out of a
    note: ssh-keygen rejects CRLF endings and a missing final newline, and
    without this check a mangled paste would be stored and only fail months
    later at load time.
    """
    if source is None:
        private = sys.stdin.read()
    elif not source.exists():
        raise KeyvaultError(f"{source} does not exist")
    else:
        private = source.read_text()

    private = private.replace("\r\n", "\n").replace("\r", "\n")
    if not private.endswith("\n"):
        private += "\n"
    if not private.lstrip().startswith("-----BEGIN"):
        raise KeyvaultError("that is not a private key")
    public_key(private)
    return private


def write(name: str, private: str, *, force: bool) -> Path:
    """Write a key and its derived public half under ~/.ssh."""
    path = key_path(name)
    if path.exists() and not force:
        raise KeyvaultError(f"{path} already exists; pass --force to overwrite")
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    path.write_text(private)
    path.chmod(0o600)
    public_path = Path(f"{path}.pub")
    public_path.write_text(f"{public_key(private)}\n")
    public_path.chmod(0o644)
    return path


def add_to_agent(private: str) -> None:
    """Load a private key into the running agent, straight from memory."""
    if not os.environ.get("SSH_AUTH_SOCK"):
        raise KeyvaultError("no ssh-agent is running (SSH_AUTH_SOCK is unset)")
    _run("ssh-add", "-", stdin=private)


def _run(*args: str, stdin: str | None = None) -> str:
    proc = subprocess.run(
        args, input=stdin, capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise KeyvaultError(f"{args[0]} failed: {proc.stderr.strip()}")
    return proc.stdout
